server:
  port: 8090

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/hotelbook}
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: reservation-service
              uri: lb://reservation-service
              predicates:
                - Path=/api/hotels/**,/api/chambres/**,/api/reservations/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/paiements/**,/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
